### PR TITLE
feat: add flag to just show package name using list command

### PR DESCRIPTION
**Pull request by kanha-gupta**
Ref #865 
## 📑 Description
Added a  flag to glasskube list command to show name of packages

Preview : 

Screenshot from 2024-06-30 04-12-07

### CODE REVIEW

**Review by kosmoz — CHANGES_REQUESTED** [review]
Hi @kanha-gupta, thanks for your PR! Unfortunately, I believe there has been a misunderstanding regarding this issue. I have updated the issue description to be a little more comprehensive and add some examples. Please let me know if you have any questions!

**Comment by kosmoz** [comment]
Hey @kanha-gupta, how are you doing? Let us know if you need any help with this task!

**Comment by kanha-gupta** [comment]
> Hey @kanha-gupta, how are you doing? Let us know if you need any help with this task!

Hi, the purpose of the command `glasskube list quickwit` would be to tell if quickwit is a part of "package" or "clusterpackage" ? or just list give output only for quickwit that is 
```
PACKAGENAME  NAMESPACE  NAME  VERSION  AUTO-UPDATE  REPOSITORY  STATUS
quickwit                                            glasskube   Not installed  
```

**Comment by kosmoz** [comment]
> > Hey @kanha-gupta, how are you doing? Let us know if you need any help with this task!
> 
> Hi, the purpose of the command `glasskube list quickwit` would be to tell if quickwit is a part of "package" or "clusterpackage" ? or just list give output only for quickwit that is
> 
> ```
> PACKAGENAME  NAMESPACE  NAME  VERSION  AUTO-UPDATE  REPOSITORY  STATUS
> quickwit                                            glasskube   Not installed  
> ```

Good question. I think this feature only makes sense for `Package`s, since there can only be at most one `ClusterPackage` for each name, but there can be multiple `Package`s that have the same `.Spec.PackageInfo.Name`. Quickwit is now a namespace-scoped package, so you can try out with that. Let me know if you have further questions.

**Pull request closed without merging**
