### PR TITLE
Added footer in the GUI with glasskube version

### PR DESCRIPTION
**Pull request by Aryakoste**
Closes https://github.com/glasskube/glasskube/issues/232

## 📑 Description

Added footer in the UI along with the glasskube version text in the center. And it also shows if new version is available or if the version is up-to-date.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Review by christophenne — CHANGES_REQUESTED** [review]
@Aryakoste thanks for the PR, good job so far. There are a few minor things to fix, please have a look at them.

**Comment by Aryakoste** [comment]
commit-lint error isnt going. Any ideas. I tried fixing but it still checking from previous commits upto latest commit.

**Comment by christophenne** [comment]
> commit-lint error isnt going. Any ideas. I tried fixing but it still checking from previous commits upto latest commit.

Please squash your commits to one commit, where the message should be in conventional commit style. Ideally please also append the issue number in the commit message in brackets, like this: (#232)
Also before doing that, run `make lint-fix` to fix linter errors. 
When you have squashed, you will need to force-push.

**Comment by kosmoz** [comment]
Hi @Aryakoste! Do you need assistence with this PR?

To squash all your commits follow these steps:
1. `git fetch origin` (update from remote)
2. `git reset --soft origin/main` (reset the branch but keep files unchanged)
3. `git add -A` (stage all changes)
4. `git commit -m "feat: description of your feature"` (create a new commit)
5. `git push --force-with-lease` (overwrite remote)

**Comment by Aryakoste** [comment]
I will submit PR today by EOD.

**Comment by christophenne** [comment]
> I will submit PR today by EOD.

Thanks. I think something went wrong there when resolving conflicts, and a lot of the changes commited to main recently would be reverted with your PR. Unfortunately I have no idea how to resolve this more elegantly than to create a new branch/PR based on the latest main. Can you find a way to fix this or should we take over?

**Comment by Aryakoste** [comment]
I will fix this and will submit a new PR.

**Comment by Aryakoste** [comment]
I have submitted a new PR:-
https://github.com/glasskube/glasskube/pull/572

**Comment by christophenne** [comment]
closed in favor of #572

**Pull request closed without merging**
