### PR TITLE
feat(ui): display latest version in package overview

### LINKED ISSUE #330: Display installed version of a package in the UI
**Is your feature request related to a problem? Please describe.**
It is not possible to determine which package is currently installed via the UI.

**Describe the solution you'd like**
- Similar to the `list`  command the installed version of a package should be displayed on the overview and detail page.
- On the detail page also display the latestVersion.
- If an update is available display the update path e.g. `v0.0.1` -> `v0.0.2`

**Describe alternatives you've considered**
Also always display the latest version.

### PR DESCRIPTION
**Pull request by hanshal101**
Closes #330
Fixes #330

## 📑 Description
This shows the LatestVersion and the Current version (if installed) on the package overview page
Images :
- When a Package is installed 
image
- When a Package is not installed 
image

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Review by kosmoz — CHANGES_REQUESTED** [review]
Looks good!

I think it would make sense to only show the "latest version" if it would make sense to upgrade to it. For this, one would have to register `semver.IsUpgradable` as a `templateFuncs` in `internal/web/templates.go` so it can be called from a template. Then it should be possible to use it in a template like this:
```html
{{ if IsUpgradable .Package.Status.Version .LatestVersion }}
<!-- show latest version here -->
{{ end }}
```

Do you think you could incorporate this change @hanshal101?

**Comment by hanshal101** [comment]
I can try this, can you give me some more information on this. And what's the actual purpose it solves.

**Comment by hanshal101** [comment]
Also I forgot the path which sends all the data to the template. Could you please guide me to the file. (Data : Manifests, Status, Package etc. In the package-detail page)

**Comment by kosmoz** [comment]
> Also I can't find the path which sends all the data to the template. Could you please guide me to the file. (Data : Manifests, Status, Package etc. In the package-detail page)

I think what you're looking for is the `packageDetail` function in `internal/web/server.go`.

> what's the actual purpose it solves.

I think, as a user I don't really care what the latest version is if I'm already using it and especially if I am using a version that is _newer_ than the latest version (the latest version is not necessarily the highest available, it's the one that was tested and reviewed).

> I can try this, can you give me some more information on this. 

If you have any more specific questions I can try to answer them! :slightly_smiling_face:

**Comment by hanshal101** [comment]
Well from your explaination I understood :
- Adding a `IsUpgrade` in the `templatesFunc`
Looking something like this:
```
"IsUpgradeble": semver.IsUpgradable,
```
- After performing this I added the htmx code as : 
```
<span>
            {{ if IsUpgradable .Package.Status.Version .LatestVersion }}
              <i> Latest Version: {{ .LatestVersion }} </i>
            {{ end }}
            <br />
            {{ if ne .Status nil }}
              <i> Current Version: {{ .Package.Status.Version }} </i>
            {{ end }}
</span>
```

Is this something we are looking for?
Here I have a small doubt. If I apply this code then we wont be able to see the `latest version` in the package which is not installed.

**Comment by kosmoz** [comment]
That looks like it might work. I think `IsUpgradable` returns true if one of the versions is empty so we should be fine here.

**Comment by hanshal101** [comment]
What about showing `LatestVersion` on packages which are not installed?

**Comment by kosmoz** [comment]
> What about showing `LatestVersion` on packages which are not installed?

In this case, the latest version should be shown. But I think your code already does this.

**Comment by hanshal101** [comment]
Hey here I made a few mistakes before in the commits but fixed it in the next commit. But still the checks have not passed as it shows the error of the past commit too. Is there any way to fix it.

**Comment by kosmoz** [comment]
`git fetch origin && git rebase origin/main`
… then test your changes, then …
`git push --force-with-lease`

**Pull request closed without merging**
