### PR TITLE
fix: made the blog images responsive

### LINKED ISSUE #1208: Adjust blog image aspect ratio to adapt to different screen sizes
**Describe the bug**
On smaller screens the new blog appearance doesn't auto-adjust the image thumbnail aspect ratio, resulting in cut off border as can be seen in the screenshot attached below. 

**To Reproduce**
Open https://glasskube.dev/blog/ on a laptop screen

**Expected behavior**
Images adjust automatically to smaller screens and borders are not cut off

**Screenshots**
Screenshot 2024-09-08 at 11 07 57

### PR DESCRIPTION
**Pull request by bishalbera**
Closes #1208 

## 📑 Description
Added media queries for different screen sizes to make the blog images responsive. I'm leaving some screenshots below.
Screenshot 2024-09-20 at 3 47 57 PM
Screenshot 2024-09-20 at 3 51 35 PM
Screenshot 2024-09-20 at 3 53 13 PM
Screenshot 2024-09-20 at 3 53 55 PM

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Review by pmig — CHANGES_REQUESTED** [review]
Thanks for contributing.

We already use break points between 996px /  997px and  576px / 557px. So we should not introduce new arbitrary breakpoints. (see: https://github.com/glasskube/glasskube/blob/main/website/src/theme/NavbarItem/NavbarWrapper/styles.module.css)

Also the main header picture on the blog page does not have rounded cornered any more.

**Comment by bishalbera** [comment]
> Thanks for contributing.
> 
> We already use break points between 996px / 997px and 576px / 557px. So we should not introduce new arbitrary breakpoints. (see: https://github.com/glasskube/glasskube/blob/main/website/src/theme/NavbarItem/NavbarWrapper/styles.module.css)
> 
> Also the main header picture on the blog page does not have rounded cornered any more.

ok so is that mean I should use those breakpoints to fix the bug? and really sorry I missed rounded corners for the latest blog . Thanks

**Comment by pmig** [comment]
> ok so is that mean I should use those breakpoints to fix the bug? 

Yes using the same breakpoints is needed. If you provided an update on the pr make sure to re request a review :-)

**Comment by bishalbera** [comment]
@pmig hey sorry for such late update . I was busy with some other stuff. I used the breakpoints used in your previously mentioned file and everything is looking fine but there is a small issue, the bottom line of the latest blog image is not aligned with read more button like it was previously. do you want me to align it then it will take me some more time? Thanks
Screenshot 2024-10-01 at 6 43 04 AM

**Review by pmig — CHANGES_REQUESTED** [review]
I still noticed a couple of issues if the browser is around 1000px wide.

 - The "rounded" corners doesn't align with the actual images.
 - Also the "main image" doesn't have rounded corners on various browser sizes, as the image and the image container have different sizes.
 
 
image

Please let us know if we should take this issue over.

**Comment by pmig** [comment]
using different source images sizes is the actual problem, so it is not really solvable grammatically.

Thanks @bishalbera for trying though <3

**Pull request closed without merging**
