### PR TITLE
docs(website): add v0.1.0 release blogpost

### PR DESCRIPTION
**Pull request by jakepage91**
## 📑 Description
Release post for v.0.1.0

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
This pic needs to be attached
dark-light

### CODE REVIEW

**Review by christophenne — APPROVED** [review]

**Comment by pmig** [comment]
@jakepage91 @christophenne could you make sure the commit is signed with the correct glasskube email and that email is added to the GitHub account?

**Review by pmig — CHANGES_REQUESTED** [review]
See comment about commit author and email association

**Comment by jakepage91** [comment]
Ahh, yeah, I signed it with my personal email since it's the email address associated to my GitHub account. Let me sign with my jake@glasskube.com address, just a sec.

**Review by pmig — APPROVED** [review]

**Comment by jakepage91** [comment]
Adding new pic for release v0.1.0 blog: 
darkspit

**Pull request merged**
