### PR TITLE
fix(cli): set autoUpdate a boolean for gk describe yaml/json output

### LINKED ISSUE #765: `autoUpdate` output in `glasskube describe --output=[yaml|json]` should be a boolean
**Is your feature request related to a problem? Please describe.**
JSON/YAML output to `glasskube describe` has been added in #717. The field `autoUpdate` is a string "Enabled" or "Disabled", but it should actually be a boolean true/false instead.

**Describe the solution you'd like**
`autoUpdate` should be a boolean.

**Describe alternatives you've considered**

**Additional context**
https://github.com/glasskube/glasskube/pull/717#discussion_r1629411787

### PR DESCRIPTION
**Pull request by doncicuto**
Closes #765 

## 📑 Description
This PR changes JSON/YAML output to `glasskube describe` so autoUpdate is a boolean value instead of a string "Enabled" or "Disabled"

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
This would be a breaking change as the output for autoUpdate has changed from a string value to a boolean value

Here's a screenshot showing the new output format:

image

### CODE REVIEW

**Review by christophenne — COMMENTED** [review]
Thanks, it works fine but just recently there was some refactoring concerning auto updates here: #772 – if it's okay for you, we would finish #772 first, and than you can rebase on main and reuse the `pkg.AutoUpdatesEnabled` function

**Comment by doncicuto** [comment]
Perfect @christophenne I'll proceed as you suggest

**Comment by christophenne** [comment]
@doncicuto the other PR is merged, so the `pkg.AutoUpdatesEnabled` is available now.

**Comment by doncicuto** [comment]
Sorry @christophenne, I screwed the commit message format

**Comment by kosmoz** [comment]
> Sorry @christophenne, I screwed the commit message format

That's no problem. We just updated our workflow and policy to put less strict requirements on PR branches. Please merge the latest commits from main to get these benefits.

**Review by christophenne — APPROVED** [review]

**Pull request merged**
