### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by Horiodino**
Closes # 

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

in `internal/controller/package_controller.go` need to do changes , does the changes make any sence ? or i should modify it

### CODE REVIEW

**Review by kosmoz — CHANGES_REQUESTED** [review]
Hi @Horiodino! First of all, please make sure that your build runs clean before submitting a PR. This usually makes the review and merge process a lot quicker! There are some build errors in your branch. You can run `make all` on your computer to check the build locally.

Please see the comments below, I found some problems with this change. Additionally, The `installer` should evaluate `Recoverable()` to determine whether it can stop waiting for the package to become ready in `awaitInstall`.

**Comment by jakepage91** [comment]
Hey @Horiodino how is the PR going? Need any additional assistance from the team?

**Comment by Horiodino** [comment]
> Hey @Horiodino how is the PR going? Need any additional assistance from the team?

hey 👋 i was just busy end sem exams , just overed today , i have added changes to the `glasskube\internal\controller\package_controller.go`  i will commit once i fix up things !

**Comment by jakepage91** [comment]
Sounds great @Horiodino! Hope you exams went well

**Pull request closed without merging**
