### PR TITLE
fix(website): velero icon url replaced with velero git source icon ur…

### LINKED ISSUE #482: Enable logo rendering on Firefox
**Is your feature request related to a problem? Please describe.**
The logos located in the [package section](https://glasskube.dev/packages/) of the website fail to render on Firefox
image

It seems to fail due to the following
```
The resource at “https://pbs.twimg.com/profile_images/1092805171938234371/CeyfzQLG_400x400.jpg” was blocked because content blocking is enabled.
```
**Describe the solution you'd like**
Make sure all visual assets render on Firefox

**Additional context**
Reference: https://developer.mozilla.org/en-US/docs/Web/Privacy/Firefox_tracking_protection

### PR DESCRIPTION
**Pull request by sumeshmurali**
...I(#482)

This commit fixes Velero icon not rendering on firefox

Closes #482 

## 📑 Description
This PR fixes the Velero icon not rendering in Firefox when using strict tracker filter or when using private window. The fix replaces the Velero icon URL from twitter image url to github icon url.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
Note that the new icon is different from the one on their website.

### CODE REVIEW

**Review by pmig — CHANGES_REQUESTED** [review]
Hi @sumeshmurali 

Thanks for creating the PR.

Using the GitHub Avatar doesn't work for velero as it would display the vmware Tanzu Logo

see:

| velero | vmware |
| -- | -- |
|  |  |


I'm not sure on how to proceed here I didn't find an offical logo on GitHub.

We could upload it here and reference it tough - by using this url: 

https://github.com/glasskube/glasskube/assets/3041752/44efa073-fd5f-47b8-9ae5-95abb33a47e7

image

**Comment by sumeshmurali** [comment]
@pmig I'll try the mentioned method. I was also doubtful about the logo.

**Comment by sumeshmurali** [comment]
@pmig Is the URL mentioned permanent? I don't know how it was uploaded so making sure it won't expire or something, Can I use the same to replace?

**Comment by pmig** [comment]
@sumeshmurali yes the url above is permanent you use it.

**Comment by sumeshmurali** [comment]
@pmig I made the changes and verified it. However, I want to point out that, the new icon is a bit resource heavy (150 KB) took a while to load compared to other icons.

**Review by kosmoz — APPROVED** [review]
Looks good to me. Regarding your concern, @sumeshmurali, I think 400x400 pixels should be OK, maybe it took noticeably longer for your because the other images were already cached by your browser?

Anyways, note to reviewers: Please "squash & merge" this PR.

**Review by pmig — APPROVED** [review]

**Comment by pmig** [comment]
LGTM @kosmoz coud you merge it?

**Pull request merged**
