### PR TITLE
feat: generate completions after brew install

### PR DESCRIPTION
**Pull request by totallyGreg**
Resolves issue with Completions introduced in https://github.com/glasskube/glasskube/pull/1192

## 📑 Description
Removes three install lines from previous commit and uses homebrew function in post_install block to generate and install the completions
[Class: Formula      — Homebrew Ruby API](https://rubydoc.brew.sh/Formula.html#generate_completions_from_executable-instance_method)

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Review by pmig — COMMENTED** [review]
@totallyGreg can you reference any application in a homebrew tap that has following post_installation script implemented so we can try it out?

I will leave the PR open until then, so we can assure it works.

**Comment by totallyGreg** [comment]
Sidero added the function here:  https://github.com/siderolabs/homebrew-tap/pull/54
And then moved it to the post_install block here:  https://github.com/siderolabs/homebrew-tap/pull/56

**Comment by pmig** [comment]
I installed talosctl and the completions did not work for me (fish shell on linux) do they completions work for you?

**Comment by totallyGreg** [comment]
They do for me in zsh.  
```shell
 [13:06] ❯ brew list talosctl
/opt/homebrew/Cellar/talosctl/1.7.5/bin/talosctl
/opt/homebrew/Cellar/talosctl/1.7.5/etc/bash_completion.d/talosctl
/opt/homebrew/Cellar/talosctl/1.7.5/sbom.spdx.json
/opt/homebrew/Cellar/talosctl/1.7.5/share/fish/vendor_completions.d/talosctl.fish
/opt/homebrew/Cellar/talosctl/1.7.5/share/zsh/site-functions/_talosctl

 [13:09] ❯ whence -v _talosctl
_talosctl is an autoload shell function from /opt/homebrew/share/zsh/site-functions/_talosctl
```

**Review by pmig — APPROVED** [review]

**Comment by pmig** [comment]
after I fixed a small typo in https://github.com/glasskube/glasskube/pull/1200 completions now should work. Do they work on your side?

**Pull request merged**
