### PR TITLE
build(cli): add completions on brew install

### PR DESCRIPTION
**Pull request by totallyGreg**
Closes # [1191](https://github.com/glasskube/glasskube/issues/1191)

## 📑 Description
add the three homebrew shell completion functions to the goreleaser.yaml brew install block

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Review by pmig — APPROVED** [review]
Thanks enhancing the developer experience

**Comment by kosmoz** [comment]
Should we do the same in the official brew repo?

**Comment by pmig** [comment]
I tried it out and it actually didn't work, so I am reverting the change now

```shell
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - completions/glasskube.bash
```

It seems that the completions are just copied, we would need to execute the cli completions command and put it into the correct folder. Else we would just create a bunch of files in the home directory for everone.

**Comment by totallyGreg** [comment]
I made a mistake.  There is a homebrew function [generate_completions_from_executable-instance_method](https://rubydoc.brew.sh/Formula.html#generate_completions_from_executable-instance_method) that can be called after install to generate and install the completions.  I have removed the install lines and created a post_install block in the goreleaser.yaml.  I'll send a new pr.

**Comment by pmig** [comment]
As the current installation is broken, I also created https://github.com/glasskube/glasskube/pull/1193 as a fallback.

**Pull request merged**
