### PR TITLE
docs: replace gif in readme with svg

### PR DESCRIPTION
**Pull request by kosmoz**
## 📑 Description
SVG looks much nicer than GIF

Preview: https://github.com/glasskube/glasskube/blob/kosmoz/readme-svg/README.md

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
I used this tool: https://github.com/marionebl/svg-term-cli

### CODE REVIEW

**Review by thschue — APPROVED** [review]
lgtm

**Review by pmig — DISMISSED** [review]
How did they merge commit passed our commit lint action? We should not merge this with this merge commit

**Comment by kosmoz** [comment]
> How did they merge commit passed our commit lint action? We should not merge this with this merge commit

Good question, I don't have an answer to that…

**Review by thekubernaut — APPROVED** [review]

**Comment by pmig** [comment]
Ok LGTM

**Pull request merged**
