### PR TITLE
feat(ui): add notification on bad request

### LINKED ISSUE #354: No error message in UI when opening entry-point fails
**Describe the bug**
Opening a package entry-point can fail for a multitude of reasons, but in no case we display an error message in the UI.

**To Reproduce**
0. Open UI
1. Install a package that has an entrypoint (e.g. cyclops)
2. Stop the package-operator
3. Delete all deployments in the package namespace
4. Click "open"

**Expected behavior**
An error message that no pod is ready to handle the entrypoint.

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: v1.28.3
 - Provider: minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: 0.0.4
 - CLI version: 0.0.4

### PR DESCRIPTION
**Pull request by hanshal101**
Fixes #354
Closes #354

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Comment by hanshal101** [comment]
Hey, @kosmoz I'm getting a build error. This error occurs when I don't handle the error with the `w.Write()` correctly?

**Comment by christophenne** [comment]
> Hey, @kosmoz I'm getting a build error. This error occurs when I don't handle the error with the `w.Write()` correctly?

Exactly, we have a linter in the buid pipeline, which checks for unchecked errors (if some method returns an error and the caller does not do anything with it). Please use `err := W.Write(...)` and print something to the console if `err != nil`.

**Comment by hanshal101** [comment]
Well I'm getting this error:
```
err := w.WriteHeader(http.StatusAccepted)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error in writing response: %v\n", err)
		}
```

Error: `w.WriteHeader(http.StatusAccepted) (no value) used as valuecompiler[TooManyValues](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#TooManyValues)`

**Comment by hanshal101** [comment]
Also, in the go Doc, I do not see any error is being returned
https://pkg.go.dev/net/http#ResponseWriter.WriteHeader

**Comment by kosmoz** [comment]
> Also, in the go Doc, I do not see any error is being returned https://pkg.go.dev/net/http#ResponseWriter.WriteHeader

WriteHeader indeed doesn't return an error, but Write does (two lines below WriteHeader)

**Comment by hanshal101** [comment]
Why this error now? 😢

**Comment by hanshal101** [comment]
It says check `Makefile` line 194.
Meanwhile line 194:
image

**Comment by kosmoz** [comment]
Run `make lint-fix`

**Comment by hanshal101** [comment]
```
PS H:\glasskube> make lint-fix
MAKE Version 5.43  Copyright (c) 1987, 2019 Embarcadero Technologies, Inc.
Error makefile 9: Command syntax error
Error makefile 11: Command syntax error
Error makefile 13: Command syntax error
Error makefile 26: Colon expected
Error makefile 144: Command syntax error
Error makefile 146: Command syntax error
Error makefile 181: Command syntax error
Error makefile 182: Command syntax error
Error makefile 193: Command syntax error
Error makefile 194: Command syntax error
Error makefile 208: Command syntax error
Error makefile 212: Command syntax error
Error makefile 217: Command syntax error
Error makefile 223: Command syntax error
*** 14 errors during make ***
```

**Comment by kosmoz** [comment]
It works for me, I use `GNU Make 4.4.1`. 

Alternatively, you can also run `npm run prettier:write` directly.

**Review by kosmoz — APPROVED** [review]
Hi @hanshal101! This looks nice, good job!

I made the following changes:
* use bootstrap `alert-dismissible` ([example](https://getbootstrap.com/docs/5.3/components/alerts/#live-example)) instead of custom dismiss implementation
* move all html from the event listener to the server-side
* removed some code that seemed unnecessary
* move error container out of `main` for cleaner semantics
* dismiss existing errors on later success

**Comment by kosmoz** [comment]
> Ohk Did you update the UI?

Yes I did :slightly_smiling_face:

**Pull request merged**
