### PR TITLE
feat(ui): open and update buttons for namespaced packages

### PR DESCRIPTION
**Pull request by christophenne**
Ref #803 

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

**Comment by christophenne** [comment]
Screenshot from 2024-07-05 11-11-10

I also made the rows hoverable, because I think already with three rows its "difficult" to make sure you press the button in the correct row, but I'm still unsure about it. 
Other than that, I think something is off in general, but I can't tell what. 

Open for any input.

**Comment by kosmoz** [comment]
> Open for any input.

Have you tried `table-striped` as well? I think it might work too, although the two are not mutually exclusive, so we can also use both

**Comment by christophenne** [comment]
> 
> Have you tried `table-striped` as well? I think it might work too, although the two are not mutually exclusive, so we can also use both

yes, but also not so sure about this: 

Screenshot from 2024-07-05 13-21-41

**Comment by kosmoz** [comment]
I see, we can think about this a little more. For now, adding `table-hover` is definitely an improvement regardless :+1:

**Review by kosmoz — APPROVED** [review]

**Pull request merged**
