### PR TITLE
docs(website): improve Blog page Layout

### LINKED ISSUE #949: Improve website blog layout
**Is your feature request related to a problem? Please describe.**
Currently our blog layout is basically the default one and not really appealing.

**Describe the solution you'd like**
After the introduction of  https://github.com/glasskube/glasskube/pull/874 and the image attribute for blog posts, we can also revamp our `/blog` page. Headlamp (also built with Docusaurus) has a very very nice Design we should get a lot of inspiration from: https://headlamp.dev/blog

**Additional context**
@jakepage91 might be needed to add the image attribute to all past blog posts.

### PR DESCRIPTION
**Pull request by prikshitsingh24**
Closes #949

## 📑 Description
Have changed the blog page layout to make it more appealing. Created a separate page which contains list of blogs with title, thumbnail and authors images and names.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### Original Blog page:
msedge_ZuzdnRrx4q

### New Blog page:
msedge_fNuUZo4Eu3

### CODE REVIEW

**Review by pmig — COMMENTED** [review]
@prikshitsingh24 thanks so much for raising the PR. Creat work. I applied the eslint fixes and did smaller ui adaptions. We still need to add blog images for the remaining posts, so the preview will look good.

**Comment by pmig** [comment]
We should also streamline the blog post cards on the front page and on the blog post list section

**Review by pmig — CHANGES_REQUESTED** [review]
@prikshitsingh24 we added images to old older blogpost, but i saw that the comment functionality broke on the blog detail page. Would you mind taking a look in order to fix it?

**Comment by prikshitsingh24** [comment]
> @prikshitsingh24 we added images to old older blogpost, but i saw that the comment functionality broke on the blog detail page. Would you mind taking a look in order to fix it?

I am not able to find the comment can you tell in which file it is.

**Comment by pmig** [comment]
> > @prikshitsingh24 we added images to old older blogpost, but i saw that the comment functionality broke on the blog detail page. Would you mind taking a look in order to fix it?
> 
> I am not able to find the comment could you tell in which file it is.

Sure, it is the comment section powered by giscus on the bottom of each blog post: 
image

**Review by prikshitsingh24 — COMMENTED** [review]
This got pushed by mistake. Previous one is the fix

**Review by pmig — CHANGES_REQUESTED** [review]
I just saw to more regressions (right is the current preferred state --> good, on the left side the regression of the PR is shown) :

1.)
image

The recent blogs section disappeared.

2.) The previous and next blog post buttons are not aligned with the blog post, but full page, they should still be aligned with the page.

image

**Comment by kosmoz** [comment]
> I just saw to more regressions (right is the current preferred state --> good, on the left side the regression of the PR is shown) :
> 
> 1.) image
> 
> The recent blogs section disappeared.
> 
> 2.) The previous and next blog post buttons are not aligned with the blog post, but full page, they should still be aligned with the page.
> 
> image

TBF, right side looks much better IMO

**Comment by prikshitsingh24** [comment]
I have fixed the 2. issue but I still not able to figure out how to add recent blog, any docs i can refer to

**Comment by pmig** [comment]
> > 2.) The previous and next blog post buttons are not aligned with the blog post, but full page, they should still be aligned with the page.
> 
> TBF, right side looks much better IMO

Yeah, you are right, I mixed up the sides, right one is obviously the desired state.

**Comment by pmig** [comment]
> I have fixed the 2nd issue but I am still not able to figure out how to add recent blog, any docs i can refer to

Mabye we can just add add a button on the left side to link to more recent blog posts. I think the default template. Blog plugin: https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-plugin-content-blog

--> https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#blogSidebarTitle

**Comment by prikshitsingh24** [comment]
> > I have fixed the 2nd issue but I am still not able to figure out how to add recent blog, any docs i can refer to
> 
> Mabye we can just add add a button on the left side to link to more recent blog posts. I think the default template. Blog plugin: https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-plugin-content-blog
> 
> --> https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#blogSidebarTitle

what will pressing that button do

**Comment by pmig** [comment]
> > > I have fixed the 2nd issue but I am still not able to figure out how to add recent blog, any docs i can refer to
> > 
> > 
> > Mabye we can just add add a button on the left side to link to more recent blog posts. I think the default template. Blog plugin: https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-plugin-content-blog
> > --> https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#blogSidebarTitle
> 
> what will pressing that button do

navigating back to the blog overview page: https://glasskube.dev/blog/

**Comment by prikshitsingh24** [comment]
msedge_ODjNUSgega
What should be the design of the button?

**Comment by pmig** [comment]
Yes looks great!

**Comment by prikshitsingh24** [comment]
> Yes looks great!

Also is it possible to create the Recent post that was in original blog  in this ?

**Comment by pmig** [comment]
> > Yes looks great!
> 
> Also is it possible to create the Recent post that was in original blog in this ? Since I don't have to much knowledge on Docusaurus.

I am also not 100%. I can take a look if you thank. Awesome how far we already went with this pr!

**Comment by prikshitsingh24** [comment]
I think i will look into it in my spare time , also the icon changed for me even if I run the original code :
msedge_3Zir2qO2gP

**Review by pmig — APPROVED** [review]
@prikshitsingh24 I approved the PR. thanks for the great work. For future PRs make sure to run `eslint --fix` to apply our formatting rules.

**Review by thekubernaut — APPROVED** [review]

**Pull request merged**
